### ISSUE TITLE
raiju candidates rpc error code DeadlineExceeded

### ISSUE THREAD

**Issue by aphex3k** [nyonson/raiju#2]
When running `raiju candidates` I receive the following error:

```shell
➜  ~ raiju candidates
raiju: rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

**Comment by aphex3k** [comment]
```shell
➜  ~ raiju candidates help
raiju: candidates doesn't take any arguments
```
Also, the help page doesn't list sub-commands but that might be a different issue. `raiju reaper` works without issues as far as I can tell.

**Comment by nyonson** [comment]
Right now only a help flag `-h` is supported for global and subcommands, but I think that would be pretty easy to add to each command. I can look into it.

```
$ raiju candidates -h                                
USAGE
  raiju candidates

Nodes are listed in descending order based on a few calculated metrics. The dominant metric is distance from the root node. Next is 'distant neighbors' which is the number of direct neighbors a node has that are distant from the root node.

FLAGS
  -assume ...               Comma separated pubkeys to assume channels too
  -clearnet=true            Filter tor-only nodes
  -limit 100                Number of results
  -min-capacity 10000000    Minimum capacity of a node
  -min-channels 5           Minimum channels of a node
  -min-distance 2           Minimum distance of a node
  -min-neighbor-distance 2  Minimum distance of a neighbor node
  -pubkey ...               Node to span out from, defaults to lnd's
  ```
  
I have never run into the `DeadlineExceeded` error so I'll try to dig into that locally, thanks for the report!

**Comment by nyonson** [comment]
Oops, didn't mean to close this yet, but hopefully the RPC timeout bump helps.

**Comment by aphex3k** [comment]
I tried with [0.3.2](https://github.com/nyonson/raiju/pkgs/container/raiju/79791243?tag=v0.3.2) and it did not change from above.
```shell
Unable to find image 'ghcr.io/nyonson/raiju:v0.3.2' locally
v0.3.2: Pulling from nyonson/raiju
0aa932d79126: Pull complete
c09a7b6be910: Pull complete
Digest: sha256:6a93c1ae065e525c2774aba788939ec46b8a2b388661dc835ee50b379c99918d
Status: Downloaded newer image for ghcr.io/nyonson/raiju:v0.3.2
raiju: rpc error: code = DeadlineExceeded desc = context deadline exceeded
```
I have about 70 peers connected. Does that matter?

> Oops, didn't mean to close this yet, but hopefully the RPC timeout bump helps.

Github does that for you when you mention an issue in a PR in context of the word _resolve_. 😃 

I also ran from source after syncing the latest changes, because I had a hunch you might have pushed the 0.3.2 package before making this change. And it indeed **solves it**!

**Comment by nyonson** [comment]
Whoops, my bad! Still ironing out the kinks in the package deployment.
